sonar.projectKey=kishorevic12_smart-inventory-frontend
sonar.organization=kishorevic12


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=smart-inventory-frontend
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src

# Keep test code out of main source metrics
sonar.exclusions=src/**/*.test.*,src/setupTests.js,src/testUtils/**
sonar.tests=src
sonar.test.inclusions=src/**/*.test.*

# Jest (Create React App) coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
